language: node_js
node_js:
  - 10
dist: xenial
os:
  - osx
  - linux
  - windows
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.electron
    - ~/.nvm
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - export JOBS=max
script:
  - npm run dist
