platform:
  - x64

install:
  - ps: Install-Product node 7 x64
  - npm install

build_script:
  - npm run dist

environment:
  GH_TOKEN:
    secure: gCu6PLWX5YVqnBO0x6C8Aej8DOukgtRg1JwR6lq1I/S7Xtzdv+S4TKSLWwuWSC2i

test: off
