platform:
  - x64

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache -> package.json'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - echo 'skip'

environment:
  GH_TOKEN:
    secure: gCu6PLWX5YVqnBO0x6C8Aej8DOukgtRg1JwR6lq1I/S7Xtzdv+S4TKSLWwuWSC2i

test: off
