name: Build

on: [push]

env:
  NODE_VERSION: 12

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: |
        sudo apt-get install libxml2-utils   \
                             icnsutils       \
                             graphicsmagick  \
                             xz-utils        \
                             build-essential \
                             libudev-dev
    - run: npm install
    - run: npm run dist

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install
    - run: npm run dist

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install
    - run: npm run dist

